### ISSUE TITLE
Unable to setup SDK with ConnectIQ 2.1.5

### ISSUE THREAD

**Issue by balane** [liias/monkey#3]
When I select the directory of the SDK, nothing happens

**Comment by liias** [comment]
Thanks for reporting. I can reproduce, will fix soon.

**Comment by liias** [comment]
Try again with plugin version 0.3.3 when it gets available in a few hours or less.

**Comment by silne30** [comment]
Hello. I am getting an issue where the trying to run the app on a simulator says "Error:Unable to find exact match for target SDK version: 1.2.1 using device: square_watch"

My SDK is 2.2.1. I tried adding -s 2.2.1 as an argument in the configuration section but that had no effect on the actual deploy script.

**Comment by liias** [comment]
Could you make a separate issue as this issue was about failing to add a SDK?

The SDK version has to be in two places:
1) In Project Structure "Target SDK version". This will add -s flag during compiling
2) In manifest.xml the minSdkVersion attribute

Also target device matters. Currently target device is configured in:
1) In Project Structure "Target Device". This will add -d flag (currently always with _sim suffix)
2) In Run Configuration "Target Device". This will append device name to the monkeydo command
3) In manifest.xml device should be in <products>

Try to "Rebuild Project" after doing changes and then run the app.
